// Generated from the approved narrative; run node scripts/sync-content.mjs. Puzzle pairings are rehearsal assignments.
export const guardians = [
  {
    id: "DEC-01",
    name: "The Moon That Stayed",
    greeting:
      "I have watched the whole evening. You may begin by noticing one thing.",
    lore: "It was invited for a moment, several centuries ago. Nobody has found a polite way to tell it the evening is over.",
    art: "moon",
    family: "vision",
    room: "October Grove",
    virtue: "Memory",
  },
  {
    id: "DEC-02",
    name: "The Gilded Root",
    greeting:
      "Names fade. Impressions last. Let us see which you intend to leave.",
    lore: "It writes the gatherings beneath its bark. This year's record contains a space it has refused to fill from memory.",
    art: "tree",
    family: "matrix",
    room: "October Grove",
    virtue: "Attention",
  },
  {
    id: "DEC-03",
    name: "The Keeper of the Pulse",
    greeting: "Yes, I can hear you thinking. Very industrious. Show me.",
    lore: "Long before this house had walls, it kept time for things with too many feet. It considers the present arrangement an improvement.",
    art: "guardian",
    family: "lanterns",
    room: "The Hollow",
    virtue: "Vitality",
  },
  {
    id: "DEC-04",
    name: "The Listener Below",
    greeting: "You may leave a moment here. Take as long as you need.",
    lore: "It remembers the sound a name makes when it is finally released. Tonight it is listening for the space that follows.",
    art: "well",
    family: "reflection",
    room: "Moon Well",
    virtue: "Discernment",
  },
  {
    id: "DEC-05",
    name: "The Unfinished Guest",
    greeting: "I meant to leave hours ago. That was several autumns back.",
    lore: "It has witnessed many turnings. At every one, it announces that this will be its last. Then someone interesting arrives.",
    art: "skull",
    family: "seal",
    room: "October Grove",
    virtue: "Restoration",
  },
  {
    id: "BUY-01",
    name: "The Black Correspondent",
    greeting:
      "I have heard three versions of you already. Make this one worth repeating.",
    lore: "It carries news between gatherings. When asked why tonight's record is unfinished, it says it never prints a name before the evidence arrives.",
    art: "raven",
    family: "token",
    room: "October Grove",
    virtue: "Perception",
  },
  {
    id: "BUY-02",
    name: "The Very Certain Owl",
    greeting: "An opinion is a start. I prefer something I can defend.",
    lore: "The owl once issued a judgment so immaculate that nobody understood it. Tonight it has been asked to keep things brief.",
    art: "owl",
    family: "witnesses",
    room: "October Grove",
    virtue: "Reason",
  },
  {
    id: "BUY-03",
    name: "The Fox of Small Print",
    greeting: "The terms are before you. I do recommend reading them.",
    lore: "The fox has never broken the Court's law. It is unbearable about this. It maintains that noticing a rule is a kind of courtesy.",
    art: "fox",
    family: "rule",
    room: "The Hollow",
    virtue: "Cunning",
  },
  {
    id: "BUY-04",
    name: "The Stag at the Edge",
    greeting: "There is room to approach. I have left it for you.",
    lore: "It stands where paths meet, keeping one clear for whoever arrives last. It believes a gathering can be judged by the space it leaves.",
    art: "stag",
    family: "thorns",
    room: "October Grove",
    virtue: "Care",
  },
  {
    id: "BUY-05",
    name: "The Hare of Almost",
    greeting: "Almost is a very useful place. I pass through it constantly.",
    lore: "It has arrived late to every gathering and somehow heard every important thing. It insists that another attempt is different from starting over.",
    art: "hare",
    family: "wheel",
    room: "The Hollow",
    virtue: "Imagination",
  },
  {
    id: "MAKE-01",
    name: "The First Knock",
    greeting: "Someone has to begin. It might as well be you.",
    lore: "It grows wherever a stranger is offered a place. The fork in its head points both inward and out.",
    art: "fork",
    family: "procession",
    room: "October Grove",
    virtue: "Welcome",
  },
  {
    id: "MAKE-02",
    name: "The Ember Guest",
    greeting: "Very well. Let us give the evening something to remember.",
    lore: "It remembers no fire, only the people who once sat around one. Its straw is cold. Its accounts of those evenings are not.",
    art: "ember",
    family: "offering",
    room: "The Hollow",
    virtue: "Generosity",
  },
  {
    id: "MAKE-03",
    name: "The Knotkeeper",
    greeting: "Nothing here stands entirely alone. Attend to what joins it.",
    lore: "It remembers a gathering by who introduced whom. Ask for a name and it will tell you a story with at least three people in it.",
    art: "knots",
    family: "untangle",
    room: "October Grove",
    virtue: "Patience",
  },
  {
    id: "MAKE-04",
    name: "The Little Host",
    greeting: "Come closer. There is enough room if everyone behaves sensibly.",
    lore: "It was made from what remained after a harvest. It has spent every autumn since insisting that there is enough to share.",
    art: "host",
    family: "constellation",
    room: "October Grove",
    virtue: "Connection",
  },
  {
    id: "MAKE-05",
    name: "The Open Door",
    greeting: "An opening is useful. Try leaving one.",
    lore: "Its veil moves whenever someone new enters the gathering. Even when the windows are shut.",
    art: "door",
    family: "sigil",
    room: "The Hollow",
    virtue: "Persistence",
  },
] as const;
export type Guardian = (typeof guardians)[number];
